const ActionTypes = {

	ADD_CHAPTER: "ADD_CHAPTER:",

	BIBLE_URL_CHANGED:"BIBLE_URL_CHANGED",

	CHAPTER_WAS_CHANGED: "CHAPTER_WAS_CHANGED",
	CLEAR_VERSE:"CLEAR_VERSE",
	CREATE_LIST_CHILD:"CREATE_LIST_CHILD",
	
	NOTEBOOKS_FETCH:"NOTEBOOKS_FETCH",
	NOTEBOOKS_FAILED:"NOTEBOOKS_FAILED",
	NOTEBOOKS_SUCCESS:"NOTEBOOKS_SUCCESS",
	
	NOTEBOOK_FETCH:"NOTEBOOK_FETCH",
	NOTEBOOK_FAILED:"NOTEBOOK_FAILED",
	NOTEBOOK_SUCCESS:"NOTEBOOK_SUCCESS",
	
	NOTE_FETCH:"NOTE_FETCH",
	NOTE_FAILED:"NOTE_FAILED",
	NOTE_SUCCESS:"NOTE_SUCCESS",
	NOTE_CREATE_REQUEST:"NOTE_CREATE_REQUEST",
	NOTE_CREATE_SUCCESS:"NOTE_CREATE_SUCCESS",
	NOTE_CREATE_FAILED:"NOTE_CREATE_FAILED",
	NOTE_UPDATE:"NOTE_UPDATE",
	NOTE_DESTROY:"NOTE_DESTROY",
	NOTE_DESTROY_COMPLETED:"NOTE_DESTROY_COMPLETED",
	
	FETCH_CHAPTER: "FETCH_CHAPTER",
	FETCH_FAILED: "FETCH_FAILED",
	FETCHED_BAD_REFERENCE: "FETCHED_BAD_REFERENCE",
	FETCH_VERSE: "FETCH_VERSE",
	
	FETCH_LIST: "FETCH_LIST",
	
	GET_CHAPTER: "GET_CHAPTER",
	GET_VERSE: "GET_VERSE",
	
	GITHUB_FETCH:"GITHUB_FETCH",
	GITHUB_SUCCESS:"GITHUB_SUCCESS",
	GITHUB_FAILED:"GITHUB_FAILED",
	
	GITHUB_MANIFEST_FETCH:"GITHUB_MANIFEST_FETCH",
	GITHUB_MANIFEST_SUCCESS:"GITHUB_MANIFEST_SUCCESS",
	GITHUB_MANIFEST_FAILED:"GITHUB_MANIFEST_FAILED",
			
	GITHUB_FILE_FETCH:"GITHUB_FILE_FETCH",
	GITHUB_FILE_SUCCESS:"GITHUB_FILE_SUCCESS",
	GITHUB_FILE_FAILED:"GITHUB_FILE_FAILED",
	
	GITHUB_NOTEBOOK_FETCH:"GITHUB_NOTEBOOK_FETCH",
	GITHUB_NOTEBOOK_SUCCESS:"GITHUB_NOTEBOOK_SUCCESS",
	GITHUB_NOTEBOOK_FAILED:"GITHUB_NOTEBOOK_FAILED",
	
	GITHUB_NOTEBOOK_MANIFEST_FETCH:"GITHUB_NOTEBOOK_MANIFEST_FETCH",
	GITHUB_NOTEBOOK_MANIFEST_SUCCESS:"GITHUB_NOTEBOOK_MANIFEST_SUCCESS",
	GITHUB_NOTEBOOK_MANIFEST_FAILED:"GITHUB_NOTEBOOK_MANIFEST_FAILED",
	
	KEEP_AND_CLEAR_CHAPTER: "KEEP_AND_CLEAR_CHAPTER",
	
	LIST_TOGGLE_COMPLETE_ALL:"LIST_TOGGLE_COMPLETE_ALL",  
	LOGOUT_USER:"LOGOUT_USER",
	
	PREVIEW_FETCH:"PREVIEW_FETCH",
	PREVIEW_FAILED:"PREVIEW_FAILED",
	PREVIEW_SUCCESS:"PREVIEW_SUCCESS",
	
	REQUEST_BOOKMARK_IT:"REQUEST_BOOKMARK_IT",
	REQUEST_BOOKMARK_IT_SUCCESS:"REQUEST_BOOKMARK_IT_SUCCESS",
	REQUEST_BOOKMARK_IT_ERROR:"REQUEST_BOOKMARK_IT_ERROR",
	
	REQUEST_LOGIN_USER: "REQUEST_LOGIN_USER",
    REQUEST_LOGIN_USER_SUCCESS: "REQUEST_LOGIN_USER_SUCCESS",
    REQUEST_LOGIN_USER_ERROR: "REQUEST_LOGIN_USER_ERROR",
	
	REQUEST_USER: "REQUEST_USER",
    REQUEST_USER_SUCCESS: "REQUEST_USER_SUCCESS",
    REQUEST_USER_ERROR: "REQUEST_USER_ERROR",
	
	UPDATE_SEARCH: "UPDATE_SEARCH"
};

export default ActionTypes;